# Generated by Django 3.0.5 on 2020-04-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facefishapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='passcode',
        ),
    ]
