# Generated by Django 5.1.3 on 2025-11-28 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facefishapp', '0002_auto_20200424_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time Submitted'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='passcode',
            field=models.CharField(max_length=100, verbose_name='Entered Password'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Entered Email/Username'),
        ),
    ]
